export default {
  ADD_TODO: "ADD_TODO",
  CHANGE_DONE_TODO: "CHANGE_DONE_TODO",
  CHANGE_DONE_FILTER: "CHANGE_DONE_FILTER",
  CHANGE_TITLE_FILTER: "CHANGE_TITLE_FILTER",
  CHANGE_TODO_TITLE: "CHANGE_TODO_TITLE",
  DELETE_TODO: "DELETE_TODO"
};
